### ISSUE TITLE
Знайти зображення Нвого Роздолу в інтернеті

### ISSUE THREAD

**Issue by Zvizda322** [Zvizda322/project-1#1]

**Comment by Zvizda322** [comment]
![image](https://user-images.githubusercontent.com/57706294/68751014-e8e8c100-0611-11ea-8b1e-fb57404f5b72.png)

**Comment by nrpk878** [comment]
https://www.google.com/search?q=%D0%BD%D0%BE%D0%B2%D0%B8%D0%B9+%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB&rlz=1C1GGRV_enUA866UA866&sxsrf=ACYBGNTV4D6YgZeah-l8ZIV_OIDY59PjUg:1573637705519&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiR98Sj8eblAhXwsYsKHZb-Bo0Q_AUIEygC&biw=1366&bih=657#imgrc=habLoFsYjh6aAM:

**Comment by nrpk878** [comment]
![image](https://user-images.githubusercontent.com/57706671/68751141-264d4e80-0612-11ea-8798-58c630441a7a.png)
